{
 "title": "Demo DevOps - PetClinic",
 "tags": [ "demo" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pods Activos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=\"petclinic\"}",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Reinicios (Restarts)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"default\", pod=~\"petclinic.*\"})",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "RAM Actual",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"default\", pod=~\"petclinic.*\"})",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "CPU Actual (Cores)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"petclinic.*\"}[1m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"petclinic.*\"}[1m]))",
     "legendFormat": "CPU (Cores)"
    }
   ]
  },
  {
   "title": "Uso de Memoria RAM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"default\", pod=~\"petclinic.*\"})",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Tráfico de Red",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"default\", pod=~\"petclinic.*\"}[1m]))",
     "legendFormat": "Recibido"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"default\", pod=~\"petclinic.*\"}[1m]))",
     "legendFormat": "Transmitido"
    }
   ]
  }
 ]
}